# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im_depend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import im_pb2 as im__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='im_depend.proto',
  package='im_depend',
  syntax='proto3',
  serialized_pb=_b('\n\x0fim_depend.proto\x12\tim_depend\x1a\x08im.proto\"D\n\nDepMessage\x12\x1e\n\x02\x65n\x18\x01 \x01(\x0e\x32\x12.im_depend.DepEnum\x12\x16\n\x04user\x18\x02 \x01(\x0b\x32\x08.im.User*%\n\x07\x44\x65pEnum\x12\x08\n\x04ZERO\x10\x00\x12\x07\n\x03ONE\x10\x01\x12\x07\n\x03TWO\x10\x02\x62\x06proto3')
  ,
  dependencies=[im__pb2.DESCRIPTOR,])

_DEPENUM = _descriptor.EnumDescriptor(
  name='DepEnum',
  full_name='im_depend.DepEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ZERO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TWO', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=110,
  serialized_end=147,
)
_sym_db.RegisterEnumDescriptor(_DEPENUM)

DepEnum = enum_type_wrapper.EnumTypeWrapper(_DEPENUM)
ZERO = 0
ONE = 1
TWO = 2



_DEPMESSAGE = _descriptor.Descriptor(
  name='DepMessage',
  full_name='im_depend.DepMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='en', full_name='im_depend.DepMessage.en', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='im_depend.DepMessage.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=108,
)

_DEPMESSAGE.fields_by_name['en'].enum_type = _DEPENUM
_DEPMESSAGE.fields_by_name['user'].message_type = im__pb2._USER
DESCRIPTOR.message_types_by_name['DepMessage'] = _DEPMESSAGE
DESCRIPTOR.enum_types_by_name['DepEnum'] = _DEPENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DepMessage = _reflection.GeneratedProtocolMessageType('DepMessage', (_message.Message,), dict(
  DESCRIPTOR = _DEPMESSAGE,
  __module__ = 'im_depend_pb2'
  # @@protoc_insertion_point(class_scope:im_depend.DepMessage)
  ))
_sym_db.RegisterMessage(DepMessage)


# @@protoc_insertion_point(module_scope)
