# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im_nested.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='im_nested.proto',
  package='im_nested',
  syntax='proto3',
  serialized_pb=_b('\n\x0fim_nested.proto\x12\tim_nested\"\xc8\x02\n\x0eInstantMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x36\n\x07nested1\x18\x02 \x01(\x0e\x32%.im_nested.InstantMessage.NestedEnum1\x12\x11\n\tsender_ip\x18\x03 \x01(\x07\x12\x1f\n\x06sender\x18\x04 \x01(\x0b\x32\x0f.im_nested.User\x12\"\n\trecipient\x18\x05 \x01(\x0b\x32\x0f.im_nested.User\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\x19\n\x11image_attachments\x18\x07 \x03(\x0c\x12%\n\x08metadata\x18\x08 \x01(\x0b\x32\x13.im_nested.MetaData\"@\n\x0bNestedEnum1\x12\x0b\n\x07\x45N_ZERO\x10\x00\x12\n\n\x06\x45N_ONE\x10\x01\x12\n\n\x06\x45N_TWO\x10\x02\x12\x0c\n\x08\x45N_THREE\x10\x03\"\'\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x13\n\x0bscreen_name\x18\x02 \x01(\t\"\x91\x03\n\x08MetaData\x12\x30\n\x07nested1\x18\x01 \x01(\x0e\x32\x1f.im_nested.MetaData.NestedEnum1\x12\x0f\n\x07latency\x18\x02 \x01(\x02\x12\x31\n\ninner_data\x18\x03 \x01(\x0b\x32\x1d.im_nested.MetaData.InnerData\x1a\xcc\x01\n\tInnerData\x12:\n\x07nested2\x18\x01 \x01(\x0e\x32).im_nested.MetaData.InnerData.NestedEnum2\x12\x0f\n\x07latency\x18\x02 \x01(\x02\x12\x30\n\x07nested1\x18\x03 \x01(\x0e\x32\x1f.im_nested.MetaData.NestedEnum1\"@\n\x0bNestedEnum2\x12\x0b\n\x07\x45N_ZERO\x10\x00\x12\n\n\x06\x45N_ONE\x10\x01\x12\n\n\x06\x45N_TWO\x10\x02\x12\x0c\n\x08\x45N_THREE\x10\x03\"@\n\x0bNestedEnum1\x12\x0b\n\x07\x45N_ZERO\x10\x00\x12\n\n\x06\x45N_ONE\x10\x01\x12\n\n\x06\x45N_TWO\x10\x02\x12\x0c\n\x08\x45N_THREE\x10\x03*W\n\x06\x43lient\x12\x12\n\x0e\x43LIENT_UNKNOWN\x10\x00\x12\x15\n\x11\x43LIENT_NATIVE_APP\x10\x01\x12\x12\n\x0e\x43LIENT_WEB_APP\x10\x02\x12\x0e\n\nCLIENT_API\x10\x03\x62\x06proto3')
)

_CLIENT = _descriptor.EnumDescriptor(
  name='Client',
  full_name='im_nested.Client',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLIENT_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLIENT_NATIVE_APP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLIENT_WEB_APP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLIENT_API', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=806,
  serialized_end=893,
)
_sym_db.RegisterEnumDescriptor(_CLIENT)

Client = enum_type_wrapper.EnumTypeWrapper(_CLIENT)
CLIENT_UNKNOWN = 0
CLIENT_NATIVE_APP = 1
CLIENT_WEB_APP = 2
CLIENT_API = 3


_INSTANTMESSAGE_NESTEDENUM1 = _descriptor.EnumDescriptor(
  name='NestedEnum1',
  full_name='im_nested.InstantMessage.NestedEnum1',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EN_ZERO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_ONE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_TWO', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_THREE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=295,
  serialized_end=359,
)
_sym_db.RegisterEnumDescriptor(_INSTANTMESSAGE_NESTEDENUM1)

_METADATA_INNERDATA_NESTEDENUM2 = _descriptor.EnumDescriptor(
  name='NestedEnum2',
  full_name='im_nested.MetaData.InnerData.NestedEnum2',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EN_ZERO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_ONE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_TWO', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_THREE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=674,
  serialized_end=738,
)
_sym_db.RegisterEnumDescriptor(_METADATA_INNERDATA_NESTEDENUM2)

_METADATA_NESTEDENUM1 = _descriptor.EnumDescriptor(
  name='NestedEnum1',
  full_name='im_nested.MetaData.NestedEnum1',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EN_ZERO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_ONE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_TWO', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_THREE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=295,
  serialized_end=359,
)
_sym_db.RegisterEnumDescriptor(_METADATA_NESTEDENUM1)


_INSTANTMESSAGE = _descriptor.Descriptor(
  name='InstantMessage',
  full_name='im_nested.InstantMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='im_nested.InstantMessage.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nested1', full_name='im_nested.InstantMessage.nested1', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender_ip', full_name='im_nested.InstantMessage.sender_ip', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='im_nested.InstantMessage.sender', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recipient', full_name='im_nested.InstantMessage.recipient', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='im_nested.InstantMessage.message', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_attachments', full_name='im_nested.InstantMessage.image_attachments', index=6,
      number=7, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='im_nested.InstantMessage.metadata', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INSTANTMESSAGE_NESTEDENUM1,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=359,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='im_nested.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='im_nested.User.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='screen_name', full_name='im_nested.User.screen_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=400,
)


_METADATA_INNERDATA = _descriptor.Descriptor(
  name='InnerData',
  full_name='im_nested.MetaData.InnerData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nested2', full_name='im_nested.MetaData.InnerData.nested2', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latency', full_name='im_nested.MetaData.InnerData.latency', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nested1', full_name='im_nested.MetaData.InnerData.nested1', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _METADATA_INNERDATA_NESTEDENUM2,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=738,
)

_METADATA = _descriptor.Descriptor(
  name='MetaData',
  full_name='im_nested.MetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nested1', full_name='im_nested.MetaData.nested1', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latency', full_name='im_nested.MetaData.latency', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inner_data', full_name='im_nested.MetaData.inner_data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_METADATA_INNERDATA, ],
  enum_types=[
    _METADATA_NESTEDENUM1,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=804,
)

_INSTANTMESSAGE.fields_by_name['nested1'].enum_type = _INSTANTMESSAGE_NESTEDENUM1
_INSTANTMESSAGE.fields_by_name['sender'].message_type = _USER
_INSTANTMESSAGE.fields_by_name['recipient'].message_type = _USER
_INSTANTMESSAGE.fields_by_name['metadata'].message_type = _METADATA
_INSTANTMESSAGE_NESTEDENUM1.containing_type = _INSTANTMESSAGE
_METADATA_INNERDATA.fields_by_name['nested2'].enum_type = _METADATA_INNERDATA_NESTEDENUM2
_METADATA_INNERDATA.fields_by_name['nested1'].enum_type = _METADATA_NESTEDENUM1
_METADATA_INNERDATA.containing_type = _METADATA
_METADATA_INNERDATA_NESTEDENUM2.containing_type = _METADATA_INNERDATA
_METADATA.fields_by_name['nested1'].enum_type = _METADATA_NESTEDENUM1
_METADATA.fields_by_name['inner_data'].message_type = _METADATA_INNERDATA
_METADATA_NESTEDENUM1.containing_type = _METADATA
DESCRIPTOR.message_types_by_name['InstantMessage'] = _INSTANTMESSAGE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['MetaData'] = _METADATA
DESCRIPTOR.enum_types_by_name['Client'] = _CLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstantMessage = _reflection.GeneratedProtocolMessageType('InstantMessage', (_message.Message,), dict(
  DESCRIPTOR = _INSTANTMESSAGE,
  __module__ = 'im_nested_pb2'
  # @@protoc_insertion_point(class_scope:im_nested.InstantMessage)
  ))
_sym_db.RegisterMessage(InstantMessage)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'im_nested_pb2'
  # @@protoc_insertion_point(class_scope:im_nested.User)
  ))
_sym_db.RegisterMessage(User)

MetaData = _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), dict(

  InnerData = _reflection.GeneratedProtocolMessageType('InnerData', (_message.Message,), dict(
    DESCRIPTOR = _METADATA_INNERDATA,
    __module__ = 'im_nested_pb2'
    # @@protoc_insertion_point(class_scope:im_nested.MetaData.InnerData)
    ))
  ,
  DESCRIPTOR = _METADATA,
  __module__ = 'im_nested_pb2'
  # @@protoc_insertion_point(class_scope:im_nested.MetaData)
  ))
_sym_db.RegisterMessage(MetaData)
_sym_db.RegisterMessage(MetaData.InnerData)


# @@protoc_insertion_point(module_scope)
